version: "3"

services:

  eventstore1:
   image: eventstore/eventstore:release-4.1.0
   env_file:
     - common-variables.env
   environment:
     - EVENTSTORE_CLUSTER_DNS=escluster.net
     - EVENTSTORE_EXT_HTTP_PORT=2113
     - EVENTSTORE_EXT_TCP_PORT=1113
     - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2113/
   ports:
     - 1113:1113
     - 2113:2113
   volumes:
     - "~/Data/eventstoredns4node/node1/:/var/lib/eventstore/"
   restart: always
   healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2113/stats || exit 1"]
      interval: 5s
      timeout: 2s
   networks:
     clusternetwork:
       aliases: 
        - escluster.net
       
  eventstore2:
   image: eventstore/eventstore:release-4.1.0
   env_file:
     - common-variables.env
   environment:
     - EVENTSTORE_CLUSTER_DNS=escluster.net
     - EVENTSTORE_EXT_HTTP_PORT=2123
     - EVENTSTORE_EXT_TCP_PORT=1123
     - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2123/
   ports:
     - 1123:1123
     - 2123:2123
   volumes:
     - "~/Data/eventstoredns4node/node2/:/var/lib/eventstore/"
   restart: always
   healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2123/stats || exit 1"]
      interval: 5s
      timeout: 2s
   networks:
     clusternetwork:
       aliases: 
        - escluster.net
   
  eventstore3:
   image: eventstore/eventstore:release-4.1.0
   env_file:
     - common-variables.env
   environment:
     - EVENTSTORE_CLUSTER_DNS=escluster.net
     - EVENTSTORE_EXT_HTTP_PORT=2133
     - EVENTSTORE_EXT_TCP_PORT=1133
     - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2133/
   ports:
     - 1133:1133
     - 2133:2133
   volumes:
     - "~/Data/eventstoredns4node/node3/:/var/lib/eventstore/"
   restart: always
   healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2133/stats || exit 1"]
      interval: 5s
      timeout: 2s
   networks:
     clusternetwork:
       aliases: 
        - escluster.net

  eventstore4:
   image: eventstore/eventstore:release-4.1.0
   env_file:
     - common-variables.env
   environment:
     - EVENTSTORE_CLUSTER_DNS=escluster.net
     - EVENTSTORE_EXT_HTTP_PORT=2143
     - EVENTSTORE_EXT_TCP_PORT=1143
     - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2143/
   ports:
     - 1143:1143
     - 2143:2143 
   volumes:
     - "~/Data/eventstoredns4node/node4/:/var/lib/eventstore/"
   restart: always
   healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2143/stats || exit 1"]
      interval: 5s
      timeout: 2s
   networks:
     clusternetwork:
       aliases: 
        - escluster.net

networks:
  clusternetwork:
    driver: bridge
